### PR TITLE
TransferClient uses kwargs explicitly. Fixes #2

### LINKED ISSUE #2: Globus v3 incompatibility
Registering doi:10.18126/M2301J yields:

```
Traceback (most recent call last):
  File "/girder/girder/api/rest.py", line 630, in endpointDecorator
    val = fun(self, path, params)
  File "/girder/girder/api/rest.py", line 1230, in POST
    return self.handleRoute(method, path, params)
  File "/girder/girder/api/rest.py", line 970, in handleRoute
    val = handler(**kwargs)
  File "/girder/girder/api/access.py", line 63, in wrapped
    return fun(*args, **kwargs)
  File "/girder/girder/api/rest.py", line 445, in wrapped
    val = fun(*args, **kwargs)
  File "/girder/girder/api/describe.py", line 709, in wrapped
    return fun(*args, **kwargs)
  File "/girder/plugins/wholetale/server/rest/dataset.py", line 241, in importData
    Job().scheduleJob(job)
  File "/girder/plugins/jobs/server/models/job.py", line 346, in scheduleJob
    events.trigger('jobs.schedule', info=job)
  File "/girder/girder/events.py", line 314, in trigger
    handler['handler'](e)
  File "/girder/plugins/jobs/server/__init__.py", line 43, in scheduleLocal
    fn(job)
  File "/girder/plugins/wholetale/server/tasks/register_dataset.py", line 33, in run
    importedData = register_dataMap(
  File "/girder/plugins/wholetale/server/lib/__init__.py", line 107, in register_dataMap
    objType, obj = provider.register(
  File "/girder/plugins/wholetale/server/lib/import_providers.py", line 86, in register
    for item in self._listRecursive(user, pid, name, base_url, progress=progress):
  File "/girder/plugins/wholetale/server/lib/globus/globus_provider.py", line 98, in _listRecursive
    tc = self.clients.getUserTransferClient(user)
  File "/girder/plugins/globus_handler/server/clients.py", line 39, in getUserTransferClient
    self.userClients[username] = TransferClient(authz)
TypeError: __init__() takes 1 positional argument but 2 were given
```

### PR DESCRIPTION
**Pull request by Xarthisius**
### How to test?
1. Register doi:10.18126/M2301J and verify that files are there.

### CODE REVIEW

**Comment by hategan** [comment]
Yay for API changes on minor version updates!

Should we pin the Globus SDK version?

**Comment by Xarthisius** [comment]
> Should we pin the Globus SDK version?

Where would be fun in that? ;-)

**Comment by hategan** [comment]
> > Should we pin the Globus SDK version?
> 
> Where would be fun in that? ;-)

We wouldn't be having this conversation, so... not much fun at all, indeed.

**Comment by craig-willis** [comment]
I registered the dataset and `cat globus_metadata.json` results in the following error:
```
[2022-02-14 15:48:56,260] ERROR:   return Cursor(self, *args, **kwargs)
[2022-02-14 15:48:56,264] WARNING: WARNING: adding swagger models without specifying resources to bind to is discouraged (dataSet).
[2022-02-14 15:52:05,893] ERROR: Traceback (most recent call last):
[2022-02-14 15:52:05,894] ERROR:   File "/girder/plugins/wt_data_manager/server/lib/transfer_manager.py", line 24, in run
[2022-02-14 15:52:05,894] ERROR:     self.transferHandler.run()
[2022-02-14 15:52:05,894] ERROR:   File "/girder/plugins/wt_data_manager/server/lib/tm_utils.py", line 34, in run
[2022-02-14 15:52:05,895] ERROR:     self.transfer()
[2022-02-14 15:52:05,895] ERROR:   File "/girder/plugins/wt_data_manager/server/lib/handlers/globus.py", line 30, in transfer
[2022-02-14 15:52:05,895] ERROR:     self._maybeStartServer()
[2022-02-14 15:52:05,896] ERROR:   File "/girder/plugins/wt_data_manager/server/lib/handlers/globus.py", line 106, in _maybeStartServer
[2022-02-14 15:52:05,896] ERROR:     self.server.start()
[2022-02-14 15:52:05,896] ERROR:   File "/girder/plugins/globus_handler/server/server.py", line 57, in start
[2022-02-14 15:52:05,897] ERROR:     (self.endpointId, self.endpointName) = self._createEndpoint()
[2022-02-14 15:52:05,897] ERROR:   File "/girder/plugins/globus_handler/server/server.py", line 212, in _createEndpoint
[2022-02-14 15:52:05,897] ERROR:     tc = self.clients.getTransferClient()
[2022-02-14 15:52:05,898] ERROR:   File "/girder/plugins/globus_handler/server/clients.py", line 27, in getTransferClient
[2022-02-14 15:52:05,898] ERROR:     self.transferClient = TransferClient(authz)
[2022-02-14 15:52:05,898] ERROR: TypeError: __init__() takes 1 positional argument but 2 were given
```

I made the same change to `server/clients.py` line 27 and get the following error: 
```
[2022-02-14 15:54:30,785] ERROR:     self.server.start()
[2022-02-14 15:54:30,786] ERROR:   File "/girder/plugins/globus_handler/server/server.py", line 57, in start
[2022-02-14 15:54:30,786] ERROR:     (self.endpointId, self.endpointName) = self._createEndpoint()
[2022-02-14 15:54:30,786] ERROR:   File "/girder/plugins/globus_handler/server/server.py", line 223, in _createEndpoint
[2022-02-14 15:54:30,786] ERROR:     _runGCCommand('%s/globusconnectpersonal' % self.gcDir, '-setup', setupKey, '-dir',
[2022-02-14 15:54:30,786] ERROR:   File "/girder/plugins/globus_handler/server/server.py", line 19, in _runGCCommand
[2022-02-14 15:54:30,786] ERROR:     raise Exception(msg)
[2022-02-14 15:54:30,786] ERROR: Exception: Command ('/opt/globusconnectpersonal/globusconnectpersonal', '-setup', 'd08493ac-3932-440c-90ff-7027b6468838', '-dir', '/home/girder/.WholeTale/0baa7c04-1ff6-4cf5-82b3-00dd47e828d9') failed with exit code 2:
[2022-02-14 15:54:30,787] ERROR: b'usage: register [-h] [--attributes [file:PATH|JSON_DATA]] [-n NAME]\n                [--description DESCRIPTION] [--owner OWNER] [-z]\n                [--high-assurance] [--atm AUTHENTICATION_TIMEOUT_MINUTES]\n                [--setup-key SETUP_KEY] [--environment {preview,production}]\n                [SETUP_KEY]\nregister: error: unrecognized arguments: -dir /home/girder/.WholeTale/0baa7c04-1ff6-4cf5-82b3-00dd47e828d9\n\nSetup did not complete successfully.\nYou may want to check /home/girder/.globusonline/lta/register.log for more information\n'
[2022-02-14 15:54:30,787] ERROR: b''
```

Which looks similar to https://github.com/whole-tale/globus_handler/issues/1?

**Review by craig-willis — APPROVED** [review]
This fixes register -- I got hung up on the transfer issue which is separate.

**Pull request merged**
